name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Copy .env
      run: php -r "file_exists('src/.env') || copy('src/.env.example', 'src/.env');"
    
    - name: Install Dependencies
      working-directory: ./src
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      working-directory: ./src
      run: php artisan key:generate

    - name: Directory Permissions
      working-directory: ./src
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      working-directory: ./src
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Update .env with SQLite configuration
      working-directory: ./src
      run: |
        echo -e "\nDB_CONNECTION=sqlite\nDB_DATABASE=database/database.sqlite" >> .env

    - name: Run migrations
      working-directory: ./src
      run: php artisan migrate

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      working-directory: ./src
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
